<h1><?= $this->_('header') ?></h1>
Lorem ipsum dolor sit amet, mus elementum eleifend erat nemo. 
Mauris sed in, risus mauris erat sit lacinia laoreet, ut maiores nec turpis. 
Aliquam sed, mollis nam id vestibulum egestas, velit nunc, condimentum ac. 
Magna purus massa. Hac felis erat a, tristique felis in ipsum et. 
Vel aliquam praesent porttitor ut erat sed, wisi elementum leo ornare urna nec, 
ut elit iaculis mauris. Nec potenti mollis velit ipsum, pulvinar augue 
voluptatibus non, per cursus aliquam, pellentesque vel laoreet imperdiet vel, 
egestas lorem a ut nulla. Tempus mauris sapien lacinia, 
facilisis elit praesent aenean malesuada pellentesque sed, 
morbi proin soluta, porttitor aliquam, proin vitae penatibus imperdiet 
elementum pede.
<h1><?= $this->_('footer') ?></h1>